import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";


export const outfit = localFont({
  variable: "--font-outfit",
  src: '../../public/fonts/Outfit-VariableFont_wght.woff2',
  display: "swap",
});

export const metadata: Metadata = {
  title: "Crumbvault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
